### ISSUE TITLE
能否提供一下简单的说明以及用法？

### ISSUE THREAD

**Issue by giveup** [gaoyb7/XFdown#1]
似乎没找到哪里登陆...
直接python config.py 也没有任何选项可以设置.
恳请不吝赐教.

**Comment by gaoyb7** [comment]
登陆模块还没写，目前只能通过设置 cookie 调用 API，基本上算是拿来自用的吧。。。

**Comment by giveup** [comment]
@gaoyb7 Github上有好几个python写的旋风客户端,全是登录挂了.
我看了下config.py,好像把您QQ暴露了...
另外,后续有考虑支持添加非BT任务功能吗?

**Comment by gaoyb7** [comment]
挂是因为现在qq那边登陆加密过程变了，原来的那套行不通，大概扫了下js源码，登陆加密过程略复杂，具体步骤也还没搞懂，目前事情比较多，等有时间再研究下。另外添加非 BT 任务功能抓包分析下就知道了，目前还没 push 上去，如果你有其他的想法，也可以 QQ 联系下我。
